### ISSUE TITLE
Clones lose other mod researches and experience.

### ISSUE THREAD

**Issue by Iivaitte** [iChun/Sync#167]
AM2 research and magic level
Witchery potion levels

I am using:
MC 1.7.10
Forge 10.13.2.1232
Witchery 0.22.0
AM2 1.0.008
sync 4.0.0

**Comment by Darkmega18** [comment]
ditto. but latest 1.7.10 forge.
Can you make an option for clones to basically just outright be extra lives that transfer the current player data to the new clone on death so to stop these problems? It's a very... Frustrating glitch...

**Comment by Iivaitte** [comment]
Actually after looking over things, this seems intentional.
