### ISSUE TITLE
Changing your username infects the region.mca files

### ISSUE THREAD

**Issue by tuskiomi** [iChun/Sync#170]
I changed my username and stepped in a shell storage, changed place with an UPDATED clone.
the constructor was not powered.
whenever I join my server I get a "netty IO exception: packet was larger than I expected, found 60708 bytes whilist reading packet 53"

**Comment by iChun** [comment]
Show the stack trace as well if you could?

**Comment by tuskiomi** [comment]
Not at a computer now, you can expect one sunday afternoon
