### ISSUE TITLE
[1.10.2] Duplication bug with soulbound items on new shells

### ISSUE THREAD

**Issue by brandonvdongen** [iChun/Sync#185]
when you have items in your inventory that are Anchored using random things spectre anchors, soulbound using enderio or using a backpack from wearable backpacks, upon entering a new shell for the first time these items get duplicated, but switching between shell storages do propperly swap this gear on/off.

so shell storage > shell constructor causes all soulbound items (and the backpack for some reason) to duplicate on the player

shell storage > shell storage works as intended without duplication errors..

**Comment by ichttt** [comment]
fixed indev, should be in the next version

**Comment by brandonvdongen** [comment]
damn you're fast, thank you!

**Comment by ichttt** [comment]
fixed by 6.0.1
