### ISSUE TITLE
[1.12.X] Sync refuses 1.12.1 with latest update

### ISSUE THREAD

**Issue by HyperMan19680** [iChun/Sync#190]
This mod, Gravity Gun, and Portal Gun, all updated recently, are refusing to work with 1.12.1. I can assume that they weren't coded to use that version.

**Comment by iChun** [comment]
Wait, are they? Is this including IChunUtil?

**Comment by iChun** [comment]
I will look into when I get home. Forge might have made a change that locks mods to a specific MC version now :/

**Comment by kihira** [comment]
It locks it to a specific mod version if the mc version accepted field thingy in mcmod.info isn't defined

**Comment by iChun** [comment]
Well, I know that now. Had a talk with lex. I'll fix this tomorrow.

**Comment by HyperMan19680** [comment]
Believe it or not, iChunUtil is the odd one out. It ran fine with 1.12.1.

**Comment by iChun** [comment]
It actually has its MC version bounds set. Since my other mods are
dependent on this I thought that would be fine, but we'll, clearly not.

**Comment by iChun** [comment]
well*

**Comment by iChun** [comment]
Fixed in version 7.0.1.
