### ISSUE TITLE
[1.12.2] Crash with ThermalExpansion

### ISSUE THREAD

**Issue by An-Sar** [iChun/Sync#192]
`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Expansion (thermalexpansion)
Caused by: java.lang.NullPointerException
    at me.ichun.mods.sync.common.core.RecipeHardcoreFactory.lambda$parse$0(RecipeHardcoreFactory.java:19)`

full crashlog: https://pastebin.com/9zseWXQu

This is with the minimum set of mods required for both Sync and ThermalExpansion to load. This has also been reported on the CoFH issue tracker: https://github.com/CoFH/Feedback/issues/567

Forge 14.23.0.2495
CodeChickenLib-1.12-3.1.3.313-universal
CoFHCore-1.12-4.3.5.13-universal
CoFHWorld-1.12-1.0.1.8-universal
iChunUtil-1.12.2-7.0.0
RedstoneFlux-1.12-2.0.1.2-universal
Sync-1.12.2-7.0.0
ThermalExpansion-1.12-5.3.5.19-universal
ThermalFoundation-1.12-2.3.5.14-universal

**Comment by ichttt** [comment]
Please search the issue tracker before posting. already fixed in dev, see #191. Will be in the next release

**Comment by An-Sar** [comment]
Sorry about that I did look but obviously missed it.
