### ISSUE TITLE
1.12.2 - the mod bugged JEI

### ISSUE THREAD

**Issue by LordHellscream** [iChun/Sync#193]
Version 7.0.0
Forge 2501

After some debugging I was able to isolate to this mod. As long as this mod is installed, JEI crafting recipe wouldn't show (processing recipe for modded block etc will show fine).

**Comment by iChun** [comment]
We had an issue with recipes in the most recent update. Once the fix is
released could you try that and get back to us?

**Comment by LordHellscream** [comment]
Sure thing.

**Comment by iChun** [comment]
7.0.1 is released. Let me know if the issue is sorted.

**Comment by LordHellscream** [comment]
this is fixed.

**Comment by denzuko** [comment]
Sync-1.10.2-6.0.1.jar also has this bug.
