### ISSUE TITLE
Clones not detecting properly EP2

### ISSUE THREAD

**Issue by Keetarin** [iChun/Sync#197]
I've just done some testing on a superflat, and it seems that everytime I create a clone it wont detect that it's finished until I relog. Very irritating bug, and honestly, until it's fixed, I won't be able to put this mod in a pack I'm building. 
P.S.: the test was on minecraft 1.12.1, sync version 7.0.1

**Comment by iChun** [comment]
@ichttt

**Comment by ichttt** [comment]
I'll look into it tomorrow

**Comment by ichttt** [comment]
I am not able to reproduce this on 1.12.2. Please try on 1.12.2 with latest forge and without other mods...

**Comment by Keetarin** [comment]
Without mods, on 1.12.1 and 1.12.2 the aforementioned bug does not show up.
However, I did accidentally discover that you can noclip through the back of the sync chamber while choosing clones in 1.12.2.
