### ISSUE TITLE
[1.12.2] Send PigWatts to Shell Constructor Crash 

### ISSUE THREAD

**Issue by GWSheridan** [iChun/Sync#199]
Trying to send PigWatts via Leadstone duct from treadmill to Shell constructor. Crashes the game

Leadstone ducts are from thermal dynamics

Crash log: https://pastebin.com/WisUt4Va

Versions
MC: 1.12.2
Forge: 14.23.2600
Sync: 1.12.2-7.0.1
Thermal Dynamics: 1.12.2-2.3.10.4

**Comment by GWSheridan** [comment]
So not a bug then

**Comment by ichttt** [comment]
No, it was a bug, but I fixed in my dev enviroment, so the next time when @iChun releases an update, the fix will be in there.

**Comment by GWSheridan** [comment]
okay thanks
