### ISSUE TITLE
[1.12.2] Crash on A Server

### ISSUE THREAD

**Issue by GWSheridan** [iChun/Sync#201]
Sync crashes on the newest forge version while on server
Works normal in game but not the server

Crash log: https://pastebin.com/9eWcsFc7

Versions
MC: 1.12.2
Forge: 14.23.2.2623
Sync: 7.0.1
iChunUtil: 7.1.4

**Comment by ichttt** [comment]
Error with latest for, please wait until the fix is pulled or use a version prior to 1.12.2-14.23.2.2622

**Comment by ichttt** [comment]
Fixed in latest forge, build 2624 will be available in a few minutes

**Comment by GWSheridan** [comment]
Thanks 👍
