### ISSUE TITLE
Tinkers Soulbound Destroys Item

### ISSUE THREAD

**Issue by KeremKoksal** [iChun/Sync#202]
Issue occurred in Forever Stranded - Lost Souls mod pack. I've created tinker tools, leveled them up and put nether star to make them soul bound but items disappeared after I die. They weren't in my inventory, they weren't in the grave. 
I've reported this issue on modpacks page and Sheridan said "Corail31 has looked at this an seems to be Sync mod." So, I'm reporting here.

I haven't found any relevant logs in the main logs directory.

Thanks

**Comment by ichttt** [comment]
So you didn't actually use sync at all? Or did you have a backup shell?

**Comment by Corail31** [comment]
I haven't done a lot of tests(as i was waiting for a private answer from Ichun), but soulbounded items are often set in the dead player, in way to transfer them in the clone event, and with Sync,  i think this event is not called on death (but called when changing from a cabin to another...)
I have the same trouble with my grave's key not transferred :
https://github.com/Corail31/tombstone_lite/issues/26

**Comment by ichttt** [comment]
This is a though one, because as soon as I fix this I get duplication bugs on other mods like baubles... I will need to look more into this

**Comment by ichttt** [comment]
@Corail31 I fixed your issue as well in dev, it will be in the next release

**Comment by Corail31** [comment]
Thanks a lot Ichttt
