### ISSUE TITLE
My player skin won't show and I can't transfer to my clone. (Minecraft 1.12.2)

### ISSUE THREAD

**Issue by Mariojacob7red** [iChun/Sync#204]
Everything else with the mod works right but when I make a clone of myself, (by clicking and with pigs), the storage container won't show my Minecraft skin. It just shows Steve and when I walk into the Shell Storage, it will show my clone and say that it's ready but, when I click on it, it won't transfer me over.
![2018-03-30_20 39 47](https://user-images.githubusercontent.com/11183321/38158473-8cc38674-345a-11e8-8511-10d65485d1bf.png)
![2018-03-30_20 39 37](https://user-images.githubusercontent.com/11183321/38158474-8cd2c954-345a-11e8-8932-98c232a24db9.png)

**Comment by ichttt** [comment]
Are you online and using latest sync and forge (7.0.2 sync and 14.23.2.2654 forge as of now)?

**Comment by Mariojacob7red** [comment]
When I took these screenshots, I was using Sync 7.0.1 and forge 14.23.1.2555. I haven't updated anything as of yet on my Minecraft instance. (I use MultiMC Launcher).

**Comment by Mariojacob7red** [comment]
I updated the mods to the exact ones you said and I'm still getting the same results. Stave in the constructor (it isn't rendering my skin), and I can't transfer over to the constructor from the storage.

**Comment by ichttt** [comment]
weird, can you upload the log file please? It's debug.log in the logs folder in your minecraft game dir

**Comment by ichttt** [comment]
Can you test without optifine pls? Optifine is known to break things in hilarios ways

**Comment by Mariojacob7red** [comment]
Sure.

**Comment by ichttt** [comment]
Ok I was able to reproduce the rendering issue but I cannot reproduce the issue with the syncing.

**Comment by Mariojacob7red** [comment]
So what was wrong with the rendering so far?

**Comment by ichttt** [comment]
They way the skinmap is received has changed since the code was written, and I didn't recognized that because I wasn't logged in so my skin was always the default one

**Comment by Mariojacob7red** [comment]
Oh ok. So, somehow my skin wasn't coming through to my game from Minecraft.net. Am I getting that right?

**Comment by ichttt** [comment]
No, it had the correct texture already(because it's your skin and you need it for 3rd person and inventory), but it didn't had the correct path to the texture.
Also please do not spam here too much, this is not a chatroom. Ping me on discord if it is not related to the issue(I'm ichttt#2790)

**Comment by Mariojacob7red** [comment]
got it.
