### ISSUE TITLE
Creating a clone and entering it duplicates inventory

### ISSUE THREAD

**Issue by TheKrister2** [iChun/Sync#205]
From what I remember the clones don't take the entire inventory with them when you transfer into them. When I created a clone it had the female skin, though that seemed to be fixed when I moved into it. However, my inventory was also duplicated, my armor, other items. When I transferred back, I experienced the same problem, my inventory was duplicated and I ended up with a second set of quite a few things.

As such, I'm pretty sure this is a bug. Though I don't know if this is some other mod interfering with this one. I'm playing on Forever Stranded Lost Souls using iChunUtil-1.12.2-7.1.4 and Sync-1.12.2-7.0.2.

**Comment by ichttt** [comment]
I worked on this for 7.0.2 and tested all kind of situations with the new behaivior to avoid dupes... I'll look into it

**Comment by TheKrister2** [comment]
Thank you, though it might very well be some form of mod incompatibility or something.

**Comment by ichttt** [comment]
I've put together a build for your to test. Just unzip the zip file and replace sync with the contained file.
[Sync-1.12.2-7.0.3BETA.zip](https://github.com/iChun/Sync/files/1890896/Sync-1.12.2-7.0.3BETA.zip)
Please tell me if you note any issues with this, I don't have much time to test this at the moment

**Comment by TheKrister2** [comment]
Sorry it took me so long for me to reply, didn't get a notification. From what I've been able to find, the mod itself does not seem to be the issue, rather there is some kind of mod incompatibility or something causing the problem. Not sure which mod(s) exactly yet though.

Thanks for taking the time to put together a build for me, wasn't really expecting that. This build does appear to fix the issues I had with duplicating inventory. The inventory does persist over clones however, but the in-inventory duplication is no longer an issue.

To make sure, I tested it alone without most of the mods active and ended up with the mod working perfectly and I can't spot anything wrong with it. In conclusion I can only say that this is a mod incompatibility issue or something similar to that.

Seriously thank you for the help though, you've been a great help. Even going as far as putting together a build for me to test. Really appreciate it.

**Comment by TheKrister2** [comment]
Because I'm pretty lazy, and the process of finding the problem is pretty tedious, it took me while (Procrastination essentially). The problem seems to be [Levels by TheXFactor117](https://minecraft.curseforge.com/projects/levels), I'm not entirely certain what _exactly_ is causing the problem, but I believe it is the soulbound mechanic in the mod. Turning it off fixes the problem, blacklisting sync also fixes the problem.

I have already created an issue on this at Levels github page to notify them.
