### ISSUE TITLE
Disableable Sky flying when syncing

### ISSUE THREAD

**Issue by Fortist** [iChun/Sync#207]
Yeah, yeah, something something lore or whatever. Can it just fade to black and switch to the synced body?
The flying thing gets really annoying.

**Comment by YaibaToKen** [comment]
Perhaps a client-side option so Players can opt out of the default behaviour, maybe a server-side option to force one of them to happen (not really useful, but someone might want it)

**Comment by Darkmega18** [comment]
Being fancy is nice, but a speed sync/fade to special effects without flying up into space and back down could be good for the sake of it getting old and such.
