### ISSUE TITLE
Player revive, baubles and Sync death prevention and bauble destruction weirdnesses reference. Also, inventory dupes when syncing normally.

### ISSUE THREAD

**Issue by Darkmega18** [iChun/Sync#214]
Due to my referencing of using sync in the same pack and my testings, just a reference to that issue.

My friend mentioned in that referenced issue also said that she was resyncing between clones just normally and her inventory was getting duped. 
Probably something related to the keeping of persistent items across instead translating into everything being carried across. As I can make a clone and switch out and the clone I sync'd to will actually have all my items as if it was just a form of fanciful teleportation. Baubles and all carried over, however cause my friend was possibly making clones after she stored and resynced to a fresh clone made using the now duplicated gear the issue was just cascading because of the aforementioned syncing of full inventories. 

https://github.com/CreativeMD/PlayerRevive/issues/14

**Comment by ichttt** [comment]
So is the issue fixed now? If not, can you try to reproduce it with https://github.com/iChun/Sync/files/1890896/Sync-1.12.2-7.0.3BETA.zip

**Comment by Darkmega18** [comment]
not sure if it was a sync issue at all. it was apparently remedied with a twilight forest dev build and was related to it logging and keeping things for charms of revival but it was acting up with the revive which would always trigger first cause of the being knocked down resulting in destroyed baubles. But twilight isn't updated yet with said fix properly so I can't start a new batch of science to see what happens with the issue fixed. :V

**Comment by ichttt** [comment]
Ok. I'm closing it for now then. If you think it is an issue with sync and it persists with a new twilight forest build feel free to reopen
