### ISSUE TITLE
I cannot transfer to my clone

### ISSUE THREAD

**Issue by HenryPDT** [iChun/Sync#220]
I can create the clone and the skin rendered perfectly, but i cannot transfer to it.

Im using minecraft version 1.12.2, ichuntil 7.2.0 and sync 7.1.0

![Untitled](https://user-images.githubusercontent.com/48423789/54096813-89427200-4401-11e9-907b-bd4e32cd0f38.png)

**Comment by ichttt** [comment]
I cannot reproduce. I see that it seems to detect you shell. Did you try the other mouse button?

**Comment by HenryPDT** [comment]
Omg, im so stupid, i switched up left and right mouse button in the settings as i prefer to place block with my left mouse more. And so i kept trying to left click so it doesnt work. It works perfectly when i clicked right mouse. Thank you so much :))
