### ISSUE TITLE
Sky Factory 4 NuclearCraft Alloy Bug(Also Ticking Crash)

### ISSUE THREAD

**Issue by Lithorn** [iChun/Sync#223]
Was making Tough Alloy when this happened.

https://pastebin.com/WXHALeU7

Now when I load the world this happens.

https://pastebin.com/MsLpHHuJ

Am backed up but I want to use that Alloy Furnace.. Dangit.

**Comment by iChun** [comment]
That's not an issue with sync, why are you posting that here?

**Comment by iChun** [comment]
Looks like a nuclearcraft issue

**Comment by Lithorn** [comment]
Its a bug I encountered in the SkyFactory 4 pack, is this not the github for it? Why wouldn't I post it here? It lets the pack maker know about the issue to warn others in-case it happens to them, but yeah NuclearCraft should also know.

**Comment by iChun** [comment]
This is the GitHub for a mod that is in the pack called Sync.

It's not the issue tracker for SF4.

**Comment by Lithorn** [comment]
Oof my bad. When I google the github this is what comes up. Apologies. Go ahead and close both tickets, Im gona search a but more for the correct github

**Comment by iChun** [comment]
The other one is relevant to sync, so I'm going to leave that one open.

**Comment by ichttt** [comment]
#222 contains the sync issue, this has nothing to do with sync.
